export const FETCH_STOCKS_SUCCESS = "FETCH_STOCKS_SUCCESS";
export const FETCH_STOCKS_FAILURE = "FETCH_STOCKS_FAILURE";
export const SET_CURR_STOCK = "SET_CURR_STOCK";
export const FETCH_STOCK_DATA_SUCCESS = "FETCH_STOCK_DATA_SUCCESS";
export const FETCH_STOCK_DATA_FAILURE = "FETCH_STOCK_DATA_FAILURE";
